/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computersciencetools;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author code
 */
public class Standard extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    int xx;
    int yy;
    double num1;
    double num2;
    double ans;
    String operator;
    private Object math;
    Brain brain= new Brain();
    
    public Standard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

     public void deletezero(){
        
      String backspace= null;
        
       if(screen.getText().length() >= 3 && screen.getText().contains(".00") ){

            StringBuilder strtext = new StringBuilder(screen.getText());
            strtext.deleteCharAt(screen.getText().length() - 1);
            strtext.deleteCharAt(screen.getText().length() - 2);
            strtext.deleteCharAt(screen.getText().length() - 3);
            backspace=strtext.toString();
            screen.setText(backspace);

        }
       }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        standard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scientific = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        programmer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        physic = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        chimistry = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        telecom = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        learntosuccess = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        colors = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        braintraining = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        timedata = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        toolbar = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        settings1 = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Content = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        screen = new javax.swing.JTextField();
        clear = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        btnRound = new javax.swing.JLabel();
        btn7 = new javax.swing.JLabel();
        btn9 = new javax.swing.JLabel();
        btn8 = new javax.swing.JLabel();
        btnPii = new javax.swing.JLabel();
        btnPourcentage = new javax.swing.JLabel();
        btnSqrt = new javax.swing.JLabel();
        btnMoin = new javax.swing.JLabel();
        btnPlus = new javax.swing.JLabel();
        btnMultiple = new javax.swing.JLabel();
        btnResult = new javax.swing.JLabel();
        btnDivide = new javax.swing.JLabel();
        btn6 = new javax.swing.JLabel();
        btn5 = new javax.swing.JLabel();
        btn4 = new javax.swing.JLabel();
        btn2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JLabel();
        btn3 = new javax.swing.JLabel();
        btnDote = new javax.swing.JLabel();
        btnPusMoin = new javax.swing.JLabel();
        btn0 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("standard");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("standard"); // NOI18N
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(0, 51, 51));
        menu.setLayout(null);

        title.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 102));
        title.setText("Code@Open Source");
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
        });
        menu.add(title);
        title.setBounds(30, 20, 230, 70);

        standard.setBackground(new java.awt.Color(0, 153, 153));
        standard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                standardMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Standard");

        javax.swing.GroupLayout standardLayout = new javax.swing.GroupLayout(standard);
        standard.setLayout(standardLayout);
        standardLayout.setHorizontalGroup(
            standardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(standardLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        standardLayout.setVerticalGroup(
            standardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, standardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(standard);
        standard.setBounds(0, 112, 310, 51);

        scientific.setBackground(new java.awt.Color(0, 102, 102));
        scientific.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scientificMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Scienific ");

        javax.swing.GroupLayout scientificLayout = new javax.swing.GroupLayout(scientific);
        scientific.setLayout(scientificLayout);
        scientificLayout.setHorizontalGroup(
            scientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scientificLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        scientificLayout.setVerticalGroup(
            scientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scientificLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(scientific);
        scientific.setBounds(0, 160, 290, 51);

        programmer.setBackground(new java.awt.Color(0, 102, 102));
        programmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                programmerMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Programmer");

        javax.swing.GroupLayout programmerLayout = new javax.swing.GroupLayout(programmer);
        programmer.setLayout(programmerLayout);
        programmerLayout.setHorizontalGroup(
            programmerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programmerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        programmerLayout.setVerticalGroup(
            programmerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programmerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(programmer);
        programmer.setBounds(0, 210, 290, 51);

        physic.setBackground(new java.awt.Color(0, 102, 102));
        physic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                physicMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Physic");

        javax.swing.GroupLayout physicLayout = new javax.swing.GroupLayout(physic);
        physic.setLayout(physicLayout);
        physicLayout.setHorizontalGroup(
            physicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(physicLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        physicLayout.setVerticalGroup(
            physicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, physicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(physic);
        physic.setBounds(0, 260, 290, 51);

        chimistry.setBackground(new java.awt.Color(0, 102, 102));
        chimistry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chimistryMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Chimistry");

        javax.swing.GroupLayout chimistryLayout = new javax.swing.GroupLayout(chimistry);
        chimistry.setLayout(chimistryLayout);
        chimistryLayout.setHorizontalGroup(
            chimistryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chimistryLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        chimistryLayout.setVerticalGroup(
            chimistryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chimistryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(chimistry);
        chimistry.setBounds(0, 310, 290, 51);

        telecom.setBackground(new java.awt.Color(0, 102, 102));
        telecom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                telecomMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telecom");

        javax.swing.GroupLayout telecomLayout = new javax.swing.GroupLayout(telecom);
        telecom.setLayout(telecomLayout);
        telecomLayout.setHorizontalGroup(
            telecomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telecomLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        telecomLayout.setVerticalGroup(
            telecomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telecomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(telecom);
        telecom.setBounds(0, 360, 290, 51);

        learntosuccess.setBackground(new java.awt.Color(0, 102, 102));
        learntosuccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                learntosuccessMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Learn to Success");

        javax.swing.GroupLayout learntosuccessLayout = new javax.swing.GroupLayout(learntosuccess);
        learntosuccess.setLayout(learntosuccessLayout);
        learntosuccessLayout.setHorizontalGroup(
            learntosuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(learntosuccessLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        learntosuccessLayout.setVerticalGroup(
            learntosuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, learntosuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(learntosuccess);
        learntosuccess.setBounds(0, 510, 290, 51);

        colors.setBackground(new java.awt.Color(0, 102, 102));
        colors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                colorsMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Colors");

        javax.swing.GroupLayout colorsLayout = new javax.swing.GroupLayout(colors);
        colors.setLayout(colorsLayout);
        colorsLayout.setHorizontalGroup(
            colorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        colorsLayout.setVerticalGroup(
            colorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(colors);
        colors.setBounds(0, 410, 290, 51);

        braintraining.setBackground(new java.awt.Color(0, 102, 102));

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Brain Training");

        javax.swing.GroupLayout braintrainingLayout = new javax.swing.GroupLayout(braintraining);
        braintraining.setLayout(braintrainingLayout);
        braintrainingLayout.setHorizontalGroup(
            braintrainingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(braintrainingLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        braintrainingLayout.setVerticalGroup(
            braintrainingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, braintrainingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(braintraining);
        braintraining.setBounds(0, 560, 290, 51);

        timedata.setBackground(new java.awt.Color(0, 102, 102));
        timedata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timedataMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Time & Data");

        javax.swing.GroupLayout timedataLayout = new javax.swing.GroupLayout(timedata);
        timedata.setLayout(timedataLayout);
        timedataLayout.setHorizontalGroup(
            timedataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timedataLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        timedataLayout.setVerticalGroup(
            timedataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timedataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(timedata);
        timedata.setBounds(0, 460, 290, 51);

        footer.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        footer.setForeground(new java.awt.Color(0, 102, 102));
        footer.setText("Version 0.01  | Code@Open Source 2018");
        menu.add(footer);
        footer.setBounds(30, 630, 250, 30);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarMouseDragged(evt);
            }
        });
        toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarMousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        close.setForeground(new java.awt.Color(0, 51, 51));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computersciencetools/icons/close.png"))); // NOI18N
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        min.setBackground(new java.awt.Color(255, 255, 255));
        min.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        min.setForeground(new java.awt.Color(0, 51, 51));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computersciencetools/icons/mino.png"))); // NOI18N
        min.setText("X");
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minMousePressed(evt);
            }
        });

        settings1.setBackground(new java.awt.Color(255, 255, 255));
        settings1.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        settings1.setForeground(new java.awt.Color(0, 51, 51));
        settings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computersciencetools/icons/sett.png"))); // NOI18N
        settings1.setText("X");

        help.setBackground(new java.awt.Color(255, 255, 255));
        help.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        help.setForeground(new java.awt.Color(0, 51, 51));
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computersciencetools/icons/help.png"))); // NOI18N
        help.setText("X");

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settings1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 742, Short.MAX_VALUE)
                .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarLayout.createSequentialGroup()
                .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toolbarLayout.createSequentialGroup()
                        .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settings1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setFocusTraversalPolicyProvider(true);
        Content.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        Content.setInheritsPopupMenu(true);
        Content.setName("content"); // NOI18N
        Content.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Standard Calculator");

        screen.setEditable(false);
        screen.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        screen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        screen.setText("0");
        screen.setBorder(null);

        clear.setBackground(new java.awt.Color(204, 102, 0));
        clear.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("C");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0)));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.setFocusable(false);
        clear.setOpaque(true);
        clear.setRequestFocusEnabled(false);
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clearMousePressed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(153, 153, 153));
        delete.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setText("←");
        delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setFocusable(false);
        delete.setOpaque(true);
        delete.setRequestFocusEnabled(false);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteMousePressed(evt);
            }
        });

        btnRound.setBackground(new java.awt.Color(153, 153, 153));
        btnRound.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnRound.setForeground(new java.awt.Color(255, 255, 255));
        btnRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRound.setText("Round");
        btnRound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnRound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRound.setFocusable(false);
        btnRound.setOpaque(true);
        btnRound.setRequestFocusEnabled(false);
        btnRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRoundMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRoundMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRoundMousePressed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(153, 153, 153));
        btn7.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn7.setText("7");
        btn7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setFocusable(false);
        btn7.setOpaque(true);
        btn7.setRequestFocusEnabled(false);
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn7MousePressed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(153, 153, 153));
        btn9.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn9.setText("9");
        btn9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setFocusable(false);
        btn9.setOpaque(true);
        btn9.setRequestFocusEnabled(false);
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn9MousePressed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(153, 153, 153));
        btn8.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn8.setText("8");
        btn8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setFocusable(false);
        btn8.setOpaque(true);
        btn8.setRequestFocusEnabled(false);
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn8MousePressed(evt);
            }
        });

        btnPii.setBackground(new java.awt.Color(153, 153, 153));
        btnPii.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnPii.setForeground(new java.awt.Color(255, 255, 255));
        btnPii.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPii.setText("π");
        btnPii.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnPii.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPii.setFocusable(false);
        btnPii.setOpaque(true);
        btnPii.setRequestFocusEnabled(false);
        btnPii.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPiiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPiiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPiiMousePressed(evt);
            }
        });

        btnPourcentage.setBackground(new java.awt.Color(153, 153, 153));
        btnPourcentage.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnPourcentage.setForeground(new java.awt.Color(255, 255, 255));
        btnPourcentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPourcentage.setText("%");
        btnPourcentage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnPourcentage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPourcentage.setFocusable(false);
        btnPourcentage.setOpaque(true);
        btnPourcentage.setRequestFocusEnabled(false);
        btnPourcentage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPourcentageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPourcentageMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPourcentageMousePressed(evt);
            }
        });

        btnSqrt.setBackground(new java.awt.Color(153, 153, 153));
        btnSqrt.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnSqrt.setForeground(new java.awt.Color(255, 255, 255));
        btnSqrt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSqrt.setText("√");
        btnSqrt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnSqrt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSqrt.setFocusable(false);
        btnSqrt.setOpaque(true);
        btnSqrt.setRequestFocusEnabled(false);
        btnSqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSqrtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSqrtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSqrtMousePressed(evt);
            }
        });

        btnMoin.setBackground(new java.awt.Color(0, 102, 102));
        btnMoin.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnMoin.setForeground(new java.awt.Color(255, 255, 255));
        btnMoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMoin.setText("-");
        btnMoin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoin.setFocusable(false);
        btnMoin.setOpaque(true);
        btnMoin.setRequestFocusEnabled(false);
        btnMoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMoinMousePressed(evt);
            }
        });

        btnPlus.setBackground(new java.awt.Color(0, 102, 102));
        btnPlus.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPlus.setText("+");
        btnPlus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlus.setFocusable(false);
        btnPlus.setOpaque(true);
        btnPlus.setRequestFocusEnabled(false);
        btnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlusMousePressed(evt);
            }
        });

        btnMultiple.setBackground(new java.awt.Color(0, 102, 102));
        btnMultiple.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnMultiple.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMultiple.setText("x");
        btnMultiple.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMultiple.setFocusable(false);
        btnMultiple.setOpaque(true);
        btnMultiple.setRequestFocusEnabled(false);
        btnMultiple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMultipleMousePressed(evt);
            }
        });

        btnResult.setBackground(new java.awt.Color(0, 102, 102));
        btnResult.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnResult.setForeground(new java.awt.Color(255, 255, 255));
        btnResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnResult.setText("=");
        btnResult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResult.setFocusable(false);
        btnResult.setOpaque(true);
        btnResult.setRequestFocusEnabled(false);
        btnResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnResultMousePressed(evt);
            }
        });

        btnDivide.setBackground(new java.awt.Color(0, 102, 102));
        btnDivide.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(255, 255, 255));
        btnDivide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDivide.setText("÷");
        btnDivide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDivide.setFocusable(false);
        btnDivide.setOpaque(true);
        btnDivide.setRequestFocusEnabled(false);
        btnDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDivideMousePressed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(153, 153, 153));
        btn6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn6.setText("6");
        btn6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setFocusable(false);
        btn6.setOpaque(true);
        btn6.setRequestFocusEnabled(false);
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn6MousePressed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(153, 153, 153));
        btn5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn5.setText("5");
        btn5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setFocusable(false);
        btn5.setOpaque(true);
        btn5.setRequestFocusEnabled(false);
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn5MousePressed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(153, 153, 153));
        btn4.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn4.setText("4");
        btn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setFocusable(false);
        btn4.setOpaque(true);
        btn4.setRequestFocusEnabled(false);
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn4MousePressed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(153, 153, 153));
        btn2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn2.setText("2");
        btn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setFocusable(false);
        btn2.setOpaque(true);
        btn2.setRequestFocusEnabled(false);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn2MousePressed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(153, 153, 153));
        btn1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn1.setText("1");
        btn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setFocusable(false);
        btn1.setOpaque(true);
        btn1.setRequestFocusEnabled(false);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn1MousePressed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(153, 153, 153));
        btn3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn3.setText("3");
        btn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setFocusable(false);
        btn3.setOpaque(true);
        btn3.setRequestFocusEnabled(false);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn3MousePressed(evt);
            }
        });

        btnDote.setBackground(new java.awt.Color(153, 153, 153));
        btnDote.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnDote.setForeground(new java.awt.Color(255, 255, 255));
        btnDote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDote.setText(".");
        btnDote.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnDote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDote.setFocusable(false);
        btnDote.setOpaque(true);
        btnDote.setRequestFocusEnabled(false);
        btnDote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDoteMousePressed(evt);
            }
        });

        btnPusMoin.setBackground(new java.awt.Color(153, 153, 153));
        btnPusMoin.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btnPusMoin.setForeground(new java.awt.Color(255, 255, 255));
        btnPusMoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPusMoin.setText("±");
        btnPusMoin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnPusMoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPusMoin.setFocusable(false);
        btnPusMoin.setOpaque(true);
        btnPusMoin.setRequestFocusEnabled(false);
        btnPusMoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPusMoinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPusMoinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPusMoinMousePressed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(153, 153, 153));
        btn0.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn0.setText("0");
        btn0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setFocusable(false);
        btn0.setOpaque(true);
        btn0.setRequestFocusEnabled(false);
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn0MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn0MousePressed(evt);
            }
        });

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ContentLayout.createSequentialGroup()
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(btnPii, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(btnPourcentage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContentLayout.createSequentialGroup()
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(btnRound, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContentLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContentLayout.createSequentialGroup()
                            .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ContentLayout.createSequentialGroup()
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ContentLayout.createSequentialGroup()
                                    .addComponent(btnDote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57)
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69)
                                    .addComponent(btnPusMoin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ContentLayout.createSequentialGroup()
                                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)
                                    .addComponent(btnMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentLayout.createSequentialGroup()
                                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)
                                    .addComponent(btnMoin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(50, 50, 50)
                            .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRound, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPii, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPourcentage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMoin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDote, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPusMoin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_toolbarMousePressed

    private void toolbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMouseDragged
      int x= evt.getXOnScreen();
      int y= evt.getYOnScreen();
       
      this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_toolbarMouseDragged

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
          System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void scientificMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scientificMousePressed
        Scientific go_to= new Scientific();
        go_to.setVisible(true);
        this.setVisible(false);
        
        
         DefaultColorEffect(standard);
         
         setColorEffect(scientific);
         
         DefaultColorEffect(programmer);
         DefaultColorEffect(physic);
         DefaultColorEffect(chimistry);
         DefaultColorEffect(telecom);
         DefaultColorEffect(programmer);
         DefaultColorEffect(colors);
         DefaultColorEffect(timedata);
         DefaultColorEffect(learntosuccess);
         DefaultColorEffect(braintraining);
         
    }//GEN-LAST:event_scientificMousePressed

    private void standardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_standardMousePressed
         
        
        
        DefaultColorEffect(scientific);
         
         setColorEffect(standard);
         
         DefaultColorEffect(programmer);
         DefaultColorEffect(physic);
         DefaultColorEffect(chimistry);
         DefaultColorEffect(telecom);
         DefaultColorEffect(programmer);
         DefaultColorEffect(colors);
         DefaultColorEffect(timedata);
         DefaultColorEffect(learntosuccess);
         DefaultColorEffect(braintraining);
    }//GEN-LAST:event_standardMousePressed

    private void programmerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programmerMousePressed
        Physic physici = new Physic();
              physic.setVisible(true);
              this.setVisible(false);
              
         Programmer go_Programmer = new Programmer ();
        go_Programmer.setVisible(true);
        
        this.setVisible(false);
        
        
        DefaultColorEffect(standard);
         
         setColorEffect(programmer);
        
         DefaultColorEffect(physic);
         DefaultColorEffect(chimistry);
         DefaultColorEffect(telecom);
         DefaultColorEffect(scientific);
         DefaultColorEffect(colors);
         DefaultColorEffect(timedata);
         DefaultColorEffect(learntosuccess);
         DefaultColorEffect(braintraining);
    }//GEN-LAST:event_programmerMousePressed

    private void physicMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_physicMousePressed
        DefaultColorEffect(standard);
         
         setColorEffect(physic);
        
         DefaultColorEffect(programmer);
         DefaultColorEffect(chimistry);
         DefaultColorEffect(telecom);
         DefaultColorEffect(scientific);
         DefaultColorEffect(colors);
         DefaultColorEffect(timedata);
         DefaultColorEffect(learntosuccess);
         DefaultColorEffect(braintraining);
    }//GEN-LAST:event_physicMousePressed

    private void chimistryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chimistryMousePressed
                DefaultColorEffect(standard);
         
         setColorEffect(chimistry);
        
         DefaultColorEffect(physic);
         DefaultColorEffect(programmer);
         DefaultColorEffect(telecom);
         DefaultColorEffect(scientific);
         DefaultColorEffect(colors);
         DefaultColorEffect(timedata);
         DefaultColorEffect(learntosuccess);
         DefaultColorEffect(braintraining);
    }//GEN-LAST:event_chimistryMousePressed

    private void telecomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telecomMousePressed
         DefaultColorEffect(standard);
         
         setColorEffect(telecom);
        
         DefaultColorEffect(physic);
         DefaultColorEffect(chimistry);
         DefaultColorEffect(programmer);
         DefaultColorEffect(scientific);
         DefaultColorEffect(colors);
         DefaultColorEffect(timedata);
         DefaultColorEffect(learntosuccess);
         DefaultColorEffect(braintraining);
    }//GEN-LAST:event_telecomMousePressed

    private void colorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorsMousePressed
         DefaultColorEffect(standard);
         
         setColorEffect(colors);
        
         DefaultColorEffect(physic);
         DefaultColorEffect(chimistry);
         DefaultColorEffect(telecom);
         DefaultColorEffect(scientific);
         DefaultColorEffect(programmer);
         DefaultColorEffect(timedata);
         DefaultColorEffect(learntosuccess);
         DefaultColorEffect(braintraining);
    }//GEN-LAST:event_colorsMousePressed

    private void timedataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timedataMousePressed
         DefaultColorEffect(standard);
         
         setColorEffect(timedata);
        
         DefaultColorEffect(physic);
         DefaultColorEffect(chimistry);
         DefaultColorEffect(telecom);
         DefaultColorEffect(scientific);
         DefaultColorEffect(colors);
         DefaultColorEffect(programmer);
         DefaultColorEffect(learntosuccess);
         DefaultColorEffect(braintraining);
    }//GEN-LAST:event_timedataMousePressed

    private void learntosuccessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learntosuccessMousePressed
         DefaultColorEffect(standard);
         
         setColorEffect(learntosuccess);
        
         DefaultColorEffect(physic);
         DefaultColorEffect(chimistry);
         DefaultColorEffect(telecom);
         DefaultColorEffect(scientific);
         DefaultColorEffect(colors);
         DefaultColorEffect(timedata);
         DefaultColorEffect(programmer);
         DefaultColorEffect(braintraining);
    }//GEN-LAST:event_learntosuccessMousePressed

    private void btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MousePressed
        String num =screen.getText()+btn1.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn1MousePressed

    private void btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MousePressed
        String num =screen.getText()+btn2.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn2MousePressed

    private void btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MousePressed
        String num =screen.getText()+btn3.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn3MousePressed

    private void btn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MousePressed
        String num =screen.getText()+btn4.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn4MousePressed

    private void btn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MousePressed
        String num =screen.getText()+btn5.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn5MousePressed

    private void btn6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MousePressed
        String num =screen.getText()+btn6.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn6MousePressed

    private void btn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MousePressed
        String num =screen.getText()+btn7.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn7MousePressed

    private void btn8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MousePressed
        String num =screen.getText()+btn8.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn8MousePressed

    private void btn9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MousePressed
        String num =screen.getText()+btn9.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn9MousePressed

    private void btn0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MousePressed
        String num =screen.getText()+btn0.getText();
        screen.setText(num);
    }//GEN-LAST:event_btn0MousePressed

    private void btnDoteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoteMousePressed
        if(!screen.getText().contains(".")){
            screen.setText(screen.getText()+btnDote.getText());
        }
    }//GEN-LAST:event_btnDoteMousePressed

    private void btnPusMoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPusMoinMousePressed
      double traitnegatif = Double.parseDouble(String.valueOf(screen.getText()));
        traitnegatif = traitnegatif * ( - 1);
        screen.setText(String.valueOf(traitnegatif));
    }//GEN-LAST:event_btnPusMoinMousePressed

    private void deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMousePressed
        String backspace= null;
       
        if(screen.getText().length() > 0 ){

            StringBuilder strtext = new StringBuilder(screen.getText());
            strtext.deleteCharAt(screen.getText().length() - 1);
            backspace=strtext.toString();
            screen.setText(backspace);

        }
    }//GEN-LAST:event_deleteMousePressed

    private void clearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMousePressed
       screen.setText("0");
    }//GEN-LAST:event_clearMousePressed

    private void btnRoundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoundMousePressed
         double round = Double.parseDouble(String.valueOf(screen.getText()));
        round = Math.round(round);
        screen.setText(String.valueOf(round));
    }//GEN-LAST:event_btnRoundMousePressed

    private void btnSqrtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMousePressed
       double squarerrot = Double.parseDouble(String.valueOf(screen.getText()));
        squarerrot = Math.sqrt(squarerrot);
        screen.setText(String.valueOf(squarerrot));
    }//GEN-LAST:event_btnSqrtMousePressed

    private void btnPiiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPiiMousePressed
       double pii;
        pii =(3.1415926535897932384626433832795);
        screen.setText(String.valueOf(pii));
    }//GEN-LAST:event_btnPiiMousePressed

    private void btnPourcentageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPourcentageMousePressed
       String getScreen = screen.getText();
       Double cnverted=Double.parseDouble(getScreen);
       Double cal = cnverted/100;
       screen.setText(cal.toString());
      
    }//GEN-LAST:event_btnPourcentageMousePressed

    private void btnPlusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMousePressed
        if(! (screen.getText().contains("-") || screen.getText().contains("+")
            || screen.getText().contains("x") ||screen.getText().contains("÷") )){

        num1=Double.parseDouble(screen.getText());
        screen.setText(null);
        operator = "+";
      
        }
    }//GEN-LAST:event_btnPlusMousePressed

    private void btnMoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoinMousePressed
        if(! (screen.getText().contains("-") || screen.getText().contains("+")
            || screen.getText().contains("x") ||screen.getText().contains("÷") )){

        num1=Double.parseDouble(screen.getText());
        screen.setText(null);
        operator = "-";
      
        }
    }//GEN-LAST:event_btnMoinMousePressed

    private void btnDivideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMousePressed
      if(! (screen.getText().contains("-") || screen.getText().contains("+")
            || screen.getText().contains("x") ||screen.getText().contains("÷") )){

        num1=Double.parseDouble(screen.getText());
        screen.setText(null);
        operator = "/";
      
        }
    }//GEN-LAST:event_btnDivideMousePressed

    private void btnMultipleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultipleMousePressed
       if(! (screen.getText().contains("-") || screen.getText().contains("+")
            || screen.getText().contains("x") ||screen.getText().contains("÷") )){

        num1=Double.parseDouble(screen.getText());
        screen.setText(null);
        operator = "x";
      
        }
    }//GEN-LAST:event_btnMultipleMousePressed

    private void btnResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultMousePressed
       String answer;
        num2=Double.parseDouble(screen.getText());

        if(operator == "+"){
            ans = num1+num2;
            answer=String.format("%.2f" ,ans);
            screen.setText(answer);
          this.deletezero();

        }else if(operator == "-"){
            ans = num1-num2;
            answer=String.format("%.2f" ,ans);
            screen.setText(answer);
          this.deletezero();
        }else if(operator == "x" ){
            ans = num1*num2;
            answer=String.format("%.2f" ,ans);
            screen.setText(answer);
           this.deletezero();
        }else if(operator == "/"){
            ans = num1/num2;
            answer=String.format("%.2f" ,ans);
            screen.setText(answer);
            this.deletezero();
        }else if(operator == "%"){
            ans = num1%num2;
            answer=String.format("%.2f" ,ans);
            screen.setText(answer);
              this.deletezero();
        }
    }//GEN-LAST:event_btnResultMousePressed

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
        btn1.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn1MouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
         btn1.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn1MouseExited

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
        btn2.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn2MouseEntered

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
        btn2.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn2MouseExited

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
        btn3.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn3MouseEntered

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
       btn3.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn3MouseExited

    private void btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseEntered
       btn4.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn4MouseEntered

    private void btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseExited
       btn4.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn4MouseExited

    private void btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseEntered
        btn5.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn5MouseEntered

    private void btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseExited
        btn5.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn5MouseExited

    private void btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseEntered
         btn6.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn6MouseEntered

    private void btn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseExited
           btn6.setBackground(new Color(153,153,153));   
    }//GEN-LAST:event_btn6MouseExited

    private void btn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseEntered
          btn7.setBackground(new Color(0,102,102));
          btn7.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn7MouseEntered

    private void btn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseExited
         btn7.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn7MouseExited

    private void btn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseEntered
          btn8.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn8MouseEntered

    private void btn8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseExited
          btn8.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn8MouseExited

    private void btn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseEntered
        btn9.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn9MouseEntered

    private void btn9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseExited
         btn9.setBackground(new Color(155,155,155));
    }//GEN-LAST:event_btn9MouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(new Color(155,155,155));
    }//GEN-LAST:event_deleteMouseExited

    private void btnSqrtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseEntered
         btnSqrt.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btnSqrtMouseEntered

    private void btnSqrtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseExited
        btnSqrt.setBackground(new Color(155,155,155));
    }//GEN-LAST:event_btnSqrtMouseExited

    private void btnDoteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoteMouseEntered
        btnDote.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btnDoteMouseEntered

    private void btnDoteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoteMouseExited
         btnDote.setBackground(new Color(155,155,155));
    }//GEN-LAST:event_btnDoteMouseExited

    private void btn0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseEntered
        btn0.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btn0MouseEntered

    private void btn0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseExited
        btn0.setBackground(new Color(155,155,155));
    }//GEN-LAST:event_btn0MouseExited

    private void btnPusMoinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPusMoinMouseEntered
       btnPusMoin.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btnPusMoinMouseEntered

    private void btnPusMoinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPusMoinMouseExited
        btnPusMoin.setBackground(new Color(155,155,155));
    }//GEN-LAST:event_btnPusMoinMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
         clear.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
         clear.setBackground(new Color(105,105,105));
    }//GEN-LAST:event_clearMouseExited

    private void btnPiiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPiiMouseEntered
         btnPii.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btnPiiMouseEntered

    private void btnPiiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPiiMouseExited
         btnPii.setBackground(new Color(105,105,105));
    }//GEN-LAST:event_btnPiiMouseExited

    private void btnPourcentageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPourcentageMouseEntered
        btnPourcentage.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btnPourcentageMouseEntered

    private void btnPourcentageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPourcentageMouseExited
        btnPourcentage.setBackground(new Color(105,105,105));
    }//GEN-LAST:event_btnPourcentageMouseExited

    private void btnRoundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoundMouseEntered
        btnRound.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btnRoundMouseEntered

    private void btnRoundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoundMouseExited
       btnRound.setBackground(new Color(105,105,105));
    }//GEN-LAST:event_btnRoundMouseExited

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
       
        Home home_redirect = new Home();    //current page
        home_redirect.setVisible(true);   //new
        this.setVisible(false);     //current windows
        
    }//GEN-LAST:event_titleMousePressed

    private void minMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMousePressed
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_minMousePressed
   

   //this take effect like hover 
   public void setColorEffect(JPanel panel){
       
       panel.setBackground(new Color(0,153,153));
   }
   public void DefaultColorEffect(JPanel panel){
       
       panel.setBackground(new Color(0,102,102));
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Standard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Standard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Standard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Standard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Standard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel braintraining;
    private javax.swing.JLabel btn0;
    private javax.swing.JLabel btn1;
    private javax.swing.JLabel btn2;
    private javax.swing.JLabel btn3;
    private javax.swing.JLabel btn4;
    private javax.swing.JLabel btn5;
    private javax.swing.JLabel btn6;
    private javax.swing.JLabel btn7;
    private javax.swing.JLabel btn8;
    private javax.swing.JLabel btn9;
    private javax.swing.JLabel btnDivide;
    private javax.swing.JLabel btnDote;
    private javax.swing.JLabel btnMoin;
    private javax.swing.JLabel btnMultiple;
    private javax.swing.JLabel btnPii;
    private javax.swing.JLabel btnPlus;
    private javax.swing.JLabel btnPourcentage;
    private javax.swing.JLabel btnPusMoin;
    private javax.swing.JLabel btnResult;
    private javax.swing.JLabel btnRound;
    private javax.swing.JLabel btnSqrt;
    private javax.swing.JPanel chimistry;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel close;
    private javax.swing.JPanel colors;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel learntosuccess;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel min;
    private javax.swing.JPanel physic;
    private javax.swing.JPanel programmer;
    private javax.swing.JPanel scientific;
    private javax.swing.JTextField screen;
    private javax.swing.JLabel settings1;
    private javax.swing.JPanel standard;
    private javax.swing.JPanel telecom;
    private javax.swing.JPanel timedata;
    private javax.swing.JLabel title;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
